### ISSUE TITLE
Error con Ubuntu (WSL) y VS Code

### ISSUE THREAD

**Issue by YagoSilvaA** [franciscovilchezv/platform-based-development#4]
Al querer abrir un archivo con "code ." desde la terminal de Ubuntu me da el siguiente error.  Antes no me ocurría este problema y podia usar dicho comando para abrir VSCode

![descarga (21)](https://user-images.githubusercontent.com/83378492/136705513-aa1677f6-695e-4e02-bf38-1b140d36c8fd.png)
:~/nodejs101$ code .

net.js:330
      err = this._handle.open(fd);
                         ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:330:26)
    at createWritableStdioStream (internal/bootstrap/switches/is_main_thread.js:72:18)
    at process.getStderr [as stderr] (internal/bootstrap/switches/is_main_thread.js:134:12)
    at console.get (internal/console/constructor.js:213:44)
    at console.value (internal/console/constructor.js:329:50)
    at console.warn (internal/console/constructor.js:363:61)
    at I.error (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:31:6143)
    at d.error (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:31:8311)
    at Ue.onUnexpectedError (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:59:57553)
    at p.unexpectedErrorHandler (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:59:54883)
    at p.onUnexpectedError (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:5:354)
    at k (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:5:615)
    at process.<anonymous> (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:59:54964)
    at process.emit (events.js:327:22)
    at process._fatalException (internal/process/execution.js:163:25) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'uv_pipe_open'
}

**Comment by franciscovilchezv** [comment]
Hmmm..  este issue va mas allá de mis conocimientos de Windows + WSL.   Aparentemente el mismo issue fue reportado en [1420](https://github.com/microsoft/vscode-remote-release/issues/1420) pero la única conclusión fue actualizar el WSL o que se arregló solito después de un Windows update.

Leyendo un poco la Web de Microsoft, una actualización al WSL que utilizamos en el curso apareció hace un par de semanas:

[Actualizar WSL](https://docs.microsoft.com/en-us/windows/wsl/install-manual)

Ahorita no tengo mi Mac con Windows a la mano, pero lo revisaré el día de mañana que la vuelvo a tener conmigo y veré de paso que tan útil es esa actualización.

Workaround por mientras es abrir el proyecto con `File > Open` como los viejos tiempos 🥺

**Comment by franciscovilchezv** [comment]
Not fixed.  Hopefully it doesn't show up in newer versions
